title: Building a Chromecast Audio Clone with an ESP32
description: Building a Chromecast Audio Clone with an ESP32
baseurl: "/chromecast-blog"
url: "https://yayaadev.github.io"

# Build settings
markdown: kramdown
theme: minima